name: Elm Check

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  elm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn run elm make
      - run: yarn run elm-format --validate src/ examples/src/
